import type { Metadata } from "next";
import { JsonLd } from "@/components/json-ld";
import { webPageSchema, breadcrumbSchema } from "@/lib/schema";

export const metadata: Metadata = {
  title: "Terms of Service — Game Name Generator Hub",
  description:
    "Terms of Service for Game Name Generator Hub. Read our terms and conditions.",
};

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl">
      <h1 className="mb-6 text-4xl font-extrabold">Terms of Service</h1>
      <p className="mb-4 text-sm text-gray-500">Last updated: June 2026</p>

      <div className="space-y-8 leading-relaxed text-gray-300">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using Game Name Generator Hub, you agree to be
            bound by these Terms of Service. If you do not agree with any part
            of these terms, please do not use our service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            2. Description of Service
          </h2>
          <p>
            Game Name Generator Hub provides fantasy name generation tools for
            personal and commercial use. Our service is provided &quot;as is&quot;
            without warranty of any kind. We reserve the right to modify or
            discontinue the service at any time.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            3. User Responsibilities
          </h2>
          <p>
            You agree to use our service only for lawful purposes. You are
            responsible for ensuring that your use of generated names complies
            with applicable laws and does not infringe on third-party rights.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            4. Intellectual Property
          </h2>
          <p>
            All names generated by our service are free to use for personal
            and commercial projects. The website design, code, and original
            content are protected by copyright. You may not reproduce, scrape,
            or redistribute our content without permission.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            5. Limitation of Liability
          </h2>
          <p>
            Game Name Generator Hub shall not be liable for any direct,
            indirect, incidental, or consequential damages arising from the use
            or inability to use our service. This includes but is not limited to
            damages for loss of data or profits.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            6. Changes to Terms
          </h2>
          <p>
            We reserve the right to update these Terms of Service at any time.
            Continued use of the service after changes constitutes acceptance of
            the new terms. Users are encouraged to review this page periodically.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            7. Contact
          </h2>
          <p>
            For questions about these Terms, contact us at
            legal@toppicksbase.com.
          </p>
        </section>
      </div>

      <JsonLd data={webPageSchema(
        "Terms of Service — Game Name Generator Hub",
        "Terms of Service for Game Name Generator Hub. Read our terms and conditions.",
        `https://toppicksbase.com/terms`
      )} />
      <JsonLd data={breadcrumbSchema([
        { name: "Home", url: "https://toppicksbase.com" },
        { name: "Terms of Service", url: `https://toppicksbase.com/terms` }
      ])} />
    </article>
  );
}
