import type { Metadata } from "next";
import { JsonLd } from "@/components/json-ld";
import { webPageSchema, breadcrumbSchema } from "@/lib/schema";

export const metadata: Metadata = {
  title: "Disclaimer — Game Name Generator Hub",
  description:
    "Disclaimer for Game Name Generator Hub. Understand the limitations and scope of our name generation service.",
};

export default function DisclaimerPage() {
  return (
    <article className="mx-auto max-w-3xl">
      <h1 className="mb-6 text-4xl font-extrabold">Disclaimer</h1>
      <p className="mb-8 text-sm text-gray-500">Last Updated: June 19, 2026</p>
      <p className="mb-4 text-sm text-gray-500">Last updated: June 2026</p>

      <div className="space-y-8 leading-relaxed text-gray-300">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            General Disclaimer
          </h2>
          <p>
            The names and content generated by Game Name Generator Hub are
            created through automated template-based processes. While we strive
            for quality and uniqueness, we make no guarantees regarding the
            suitability, originality, or legal clearance of any generated names
            for specific uses.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            No Guarantee of Uniqueness
          </h2>
          <p>
            Due to the deterministic nature of our generation system, names may
            contain patterns or elements shared across multiple generators. We
            recommend users verify the uniqueness of names before using them in
            published works, trademarks, or commercial products.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            Fantasy Content
          </h2>
          <p>
            All content on this website, including names, lore, and
            descriptions, is fictional and intended for entertainment and
            creative purposes only. Any resemblance to real persons, places, or
            events is purely coincidental.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            Advertising Disclosure
          </h2>
          <p>
            This website may display advertisements through third-party
            advertising networks such as Google AdSense. We are not responsible
            for the content of advertisements or the products and services they
            promote. Clicking on advertisements is at your own discretion.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            External Links
          </h2>
          <p>
            Our website may contain links to external websites. We are not
            responsible for the content, accuracy, or practices of any
            third-party websites. Users should review the privacy policies and
            terms of any external sites they visit.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            Contact
          </h2>
          <p>
            If you have questions about this disclaimer, please contact us at
            legal@toppicksbase.com.
          </p>
        </section>
      </div>

      <JsonLd data={webPageSchema(
        "Disclaimer — Game Name Generator Hub",
        "Disclaimer for Game Name Generator Hub. Understand the limitations and scope of our name generation service.",
        `https://toppicksbase.com/disclaimer`
      )} />
      <JsonLd data={breadcrumbSchema([
        { name: "Home", url: "https://toppicksbase.com" },
        { name: "Disclaimer", url: `https://toppicksbase.com/disclaimer` }
      ])} />
    </article>
  );
}
