import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "@/components/json-ld";
import { faqSchema, webPageSchema, breadcrumbSchema } from "@/lib/schema";

export const metadata: Metadata = {
  alternates: { canonical: "https://toppicksbase.com/faq" },
  title: "Frequently Asked Questions — Game Name Generator Hub",
  description: "Find answers to common questions about our fantasy name generators, how to use them, naming tips, and more. Comprehensive FAQ for worldbuilders, RPG players, and writers.",
};

const faqs = [
  { question: "What is Game Name Generator Hub?", answer: "Game Name Generator Hub is the internet's largest fantasy name generation platform, offering over 4,500 unique name generators for worldbuilders, dungeon masters, RPG players, writers, and game developers. We cover kingdoms, empires, clans, guilds, characters, cities, dungeons, NPCs, monsters, creatures, ships, and more — spanning 20 themes and 15 fantasy races." },
  { question: "How do I use the name generator?", answer: "Simply browse our categories or search for the type of name you need. Each generator page provides 100 unique names with meanings and lore. You can refresh for new names, bookmark your favorites, and explore related generators for more inspiration. Every generator is free to use with no registration required." },
  { question: "Are the generated names unique?", answer: "Yes. Each generator uses a deterministic algorithm seeded by the specific combination of theme, race, and context. This means every page consistently generates the same set of 100 names — you can bookmark pages and always find the same names when you return. Across all 4,500 generators, you get access to over 450,000 unique fantasy names." },
  { question: "Can I use these names commercially?", answer: "Yes. All names generated by our platform are algorithmically created and carry no copyright restrictions. You can freely use them in your games, books, worldbuilding projects, commercial products, and creative works. We do not claim ownership over any generated names." },
  { question: "What categories of name generators do you offer?", answer: "We offer 17 major categories: Kingdom Names, Clan Names, Guild Names, Dragon Names, Demon Names, Angel Names, Vampire Names, Orc Names, Empire Names, Elf Names, Character Names, City Names, Dungeon Names, NPC Names, Monster Names, Creature Names, and Ship Names. Each category includes a hub page with curated content and dozens of specialized landing pages." },
  { question: "How accurate are the name meanings?", answer: "Name meanings are generated based on linguistic patterns and fantasy conventions, not historical etymology. They are designed to inspire worldbuilding and storytelling — not as academic references. Many names blend word roots from existing languages with original fantasy constructions to create evocative and memorable meanings." },
  { question: "Do you offer naming guides?", answer: "Yes. Many of our category hub pages and landing pages include naming guides with best practices, common mistakes to avoid, phonetic rules, and cultural context tips. We also publish regular blog articles on naming techniques for fantasy worldbuilding, RPG creation, and game development." },
  { question: "Is this website free?", answer: "Yes, Game Name Generator Hub is completely free to use. We support the site through advertising. You can browse, generate, and bookmark names without any cost or account creation." },
  { question: "How often is the site updated?", answer: "We add new name generators, landing pages, and blog content daily. Our automated content system ensures we continuously expand our coverage of fantasy naming niches while maintaining quality standards. Check back regularly for new categories and generators." },
  { question: "Can I request a specific type of name generator?", answer: "We welcome suggestions. If you need a specific type of name generator that we do not currently offer, please reach out through our Contact page. While we cannot guarantee every request will be fulfilled, we prioritize additions based on community demand and search volume." },
  { question: "How do I find related name generators?", answer: "Every generator page includes a 'Related Generators' section showing 12 thematically connected generators. Our 'People Also Search' module suggests additional keywords and topics. The internal linking system connects generators across categories, making it easy to discover relevant tools." },
  { question: "Is the site mobile-friendly?", answer: "Yes. Game Name Generator Hub is built with a responsive design that works on desktop, tablet, and mobile devices. All generators, navigation, and content are optimized for all screen sizes." },
];

export default function FAQPage() {
  return (
    <article className="mx-auto max-w-3xl">
      <h1 className="mb-2 text-4xl font-extrabold">Frequently Asked Questions</h1>
      <p className="mb-8 text-sm text-gray-500">Last Updated: June 19, 2026</p>

      <p className="mb-8 leading-relaxed text-gray-300">
        Find answers to the most common questions about Game Name Generator Hub. If you cannot find what you are looking for, please visit our <Link href="/contact" className="text-blue-400 underline hover:text-blue-300">Contact page</Link>.
      </p>

      <div className="space-y-6">
        {faqs.map((faq, i) => (
          <section key={i} className="rounded-xl border border-gray-800 bg-gray-900/50 p-6">
            <h2 className="mb-3 text-lg font-semibold text-white">{i + 1}. {faq.question}</h2>
            <p className="leading-relaxed text-gray-300">{faq.answer}</p>
          </section>
        ))}
      </div>

      <section className="mt-12 rounded-xl border border-gray-800 bg-gray-900/50 p-6 text-center">
        <h2 className="mb-3 text-xl font-bold text-white">Still have questions?</h2>
        <p className="mb-4 text-gray-300">Visit our Contact page — we typically respond within 24 hours.</p>
        <Link href="/contact" className="inline-block rounded-lg bg-blue-600 px-6 py-3 font-medium text-white hover:bg-blue-500 transition">
          Contact Us
        </Link>
      </section>

      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={webPageSchema("Frequently Asked Questions — Game Name Generator Hub", "Find answers to common questions about our fantasy name generators.", "https://toppicksbase.com/faq")} />
      <JsonLd data={breadcrumbSchema([
        { name: "Home", url: "https://toppicksbase.com/" },
        { name: "FAQ", url: "https://toppicksbase.com/faq" },
      ])} />
    </article>
  );
}
